export let products = [
  { id: 1, title: "The Alchemist", author: "Paulo Coelho", price: 399, tag: "fiction" },
  { id: 2, title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", price: 499, tag: "finance" },
  { id: 3, title: "Atomic Habits", author: "James Clear", price: 450, tag: "self-help" },
  { id: 4, title: "The Power of Your Subconscious Mind", author: "Joseph Murphy", price: 299, tag: "self-help" },
  { id: 5, title: "Ikigai", author: "Héctor García", price: 350, tag: "self-help" },
  { id: 6, title: "The Psychology of Money", author: "Morgan Housel", price: 500, tag: "finance" },
  { id: 7, title: "Think and Grow Rich", author: "Napoleon Hill", price: 550, tag: "self-help" },
  { id: 8, title: "Deep Work", author: "Cal Newport", price: 420, tag: "productivity" },
  { id: 9, title: "The Monk Who Sold His Ferrari", author: "Robin Sharma", price: 480, tag: "self-help" },
  { id: 10, title: "Can't Hurt Me", author: "David Goggins", price: 600, tag: "biography" },
  { id: 11, title: "Start With Why", author: "Simon Sinek", price: 530, tag: "leadership" },
  { id: 12, title: "Zero to One", author: "Peter Thiel", price: 499, tag: "startup" },
  { id: 13, title: "The Lean Startup", author: "Eric Ries", price: 550, tag: "startup" },
  { id: 14, title: "Rework", author: "Jason Fried", price: 470, tag: "business" },
  { id: 15, title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", price: 420, tag: "self-help" },
  { id: 16, title: "You Can Win", author: "Shiv Khera", price: 490, tag: "self-help" },
  { id: 17, title: "The Secret", author: "Rhonda Byrne", price: 530, tag: "spiritual" },
  { id: 18, title: "Sapiens", author: "Yuval Noah Harari", price: 700, tag: "history" },
  { id: 19, title: "Homo Deus", author: "Yuval Noah Harari", price: 750, tag: "future" },
  { id: 20, title: "21 Lessons for the 21st Century", author: "Yuval Noah Harari", price: 680, tag: "society" },
  { id: 21, title: "The 5 AM Club", author: "Robin Sharma", price: 620, tag: "self-help" },
  { id: 22, title: "The Magic of Thinking Big", author: "David J. Schwartz", price: 540, tag: "self-help" },
  { id: 23, title: "Tools of Titans", author: "Tim Ferriss", price: 800, tag: "productivity" },
  { id: 24, title: "The 4-Hour Workweek", author: "Tim Ferriss", price: 750, tag: "lifestyle" },
  { id: 25, title: "Grit", author: "Angela Duckworth", price: 600, tag: "psychology" },
  { id: 26, title: "Mindset", author: "Carol S. Dweck", price: 590, tag: "psychology" },
  { id: 27, title: "Dare to Lead", author: "Brené Brown", price: 650, tag: "leadership" },
  { id: 28, title: "How to Win Friends and Influence People", author: "Dale Carnegie", price: 580, tag: "self-help" },
  { id: 29, title: "The Art of War", author: "Sun Tzu", price: 500, tag: "strategy" },
  { id: 30, title: "The One Thing", author: "Gary Keller", price: 570, tag: "productivity" },
  { id: 31, title: "The 10X Rule", author: "Grant Cardone", price: 690, tag: "motivation" },
  { id: 32, title: "Purple Cow", author: "Seth Godin", price: 520, tag: "marketing" },
  { id: 33, title: "Hooked", author: "Nir Eyal", price: 550, tag: "product" },
  { id: 34, title: "Made to Stick", author: "Chip Heath & Dan Heath", price: 600, tag: "communication" },
  { id: 35, title: "The Hard Thing About Hard Things", author: "Ben Horowitz", price: 680, tag: "startup" },
  { id: 36, title: "Measure What Matters", author: "John Doerr", price: 640, tag: "business" },
  { id: 37, title: "The Ride of a Lifetime", author: "Robert Iger", price: 590, tag: "biography" },
  { id: 38, title: "Shoe Dog", author: "Phil Knight", price: 720, tag: "biography" },
  { id: 39, title: "Good to Great", author: "Jim Collins", price: 750, tag: "business" },
  { id: 40, title: "The Innovator's Dilemma", author: "Clayton Christensen", price: 700, tag: "innovation" },
  { id: 41, title: "Blue Ocean Strategy", author: "W. Chan Kim", price: 670, tag: "strategy" },
  { id: 42, title: "The Design of Everyday Things", author: "Don Norman", price: 650, tag: "design" },
  { id: 43, title: "The Elements of User Experience", author: "Jesse James Garrett", price: 590, tag: "design" },
  { id: 44, title: "Steal Like an Artist", author: "Austin Kleon", price: 450, tag: "creativity" },
  { id: 45, title: "Show Your Work!", author: "Austin Kleon", price: 480, tag: "creativity" },
  { id: 46, title: "The War of Art", author: "Steven Pressfield", price: 530, tag: "creativity" },
  { id: 47, title: "So Good They Can't Ignore You", author: "Cal Newport", price: 510, tag: "career" },
  { id: 48, title: "Drive", author: "Daniel H. Pink", price: 550, tag: "motivation" },
  { id: 49, title: "The Dip", author: "Seth Godin", price: 460, tag: "decision-making" },
  { id: 50, title: "Linchpin", author: "Seth Godin", price: 580, tag: "career" },
  { id: 51, title: "The Everything Store", author: "Brad Stone", price: 600, tag: "biography" },
  { id: 52, title: "The Bezos Letters", author: "Steve Anderson", price: 620, tag: "biography" },
  { id: 53, title: "The Lean UX", author: "Jeff Gothelf", price: 540, tag: "design" },
  { id: 54, title: "Deep Learning", author: "Ian Goodfellow", price: 950, tag: "technology" },
  { id: 55, title: "Artificial Intelligence", author: "Stuart Russell", price: 890, tag: "technology" },
  { id: 56, title: "The Algorithm Design Manual", author: "Steven S. Skiena", price: 990, tag: "technology" },
  { id: 57, title: "Designing Data-Intensive Applications", author: "Martin Kleppmann", price: 1050, tag: "technology" },
  { id: 58, title: "Computer Networking", author: "James F. Kurose", price: 880, tag: "technology" },
  { id: 59, title: "Cracking the Coding Interview", author: "Gayle Laakmann McDowell", price: 750, tag: "coding" },
  { id: 60, title: "Eloquent JavaScript", author: "Marijn Haverbeke", price: 500, tag: "coding" },
  // Already tagged:
  { id: 61, title: "Sherlock Holmes - Collector's Edition", author: "Arthur Conan Doyle", price: 1299, limitedEdition: true, tag: "classic" },
  { id: 62, title: "Harry Potter - 20th Anniversary Edition", author: "J.K. Rowling", price: 1999, limitedEdition: true, tag: "fantasy" },
  { id: 63, title: "The Hobbit - Illustrated Edition", author: "J.R.R. Tolkien", price: 1599, limitedEdition: true, tag: "fantasy" },
  { id: 64, title: "Game of Thrones - Leather Bound Set", author: "George R.R. Martin", price: 2999, limitedEdition: true, tag: "fantasy" },
  { id: 65, title: "Lord of the Rings - Gold Embossed Edition", author: "J.R.R. Tolkien", price: 2499, limitedEdition: true, tag: "fantasy" },
  { id: 66, title: "Steve Jobs - Special Edition", author: "Walter Isaacson", price: 1799, limitedEdition: true, tag: "biography" },
  { id: 67, title: "Leonardo da Vinci - Deluxe Edition", author: "Walter Isaacson", price: 1999, limitedEdition: true, tag: "biography" },
  { id: 68, title: "The Great Gatsby - Leather Bound", author: "F. Scott Fitzgerald", price: 999, limitedEdition: true, tag: "classic" },
  { id: 69, title: "Pride and Prejudice - Collector’s Edition", author: "Jane Austen", price: 1099, limitedEdition: true, tag: "classic" },
  { id: 70, title: "To Kill a Mockingbird - Limited Run", author: "Harper Lee", price: 1199, limitedEdition: true, tag: "classic" },
  // Tags are already added below:
  { id: 71, title: "Hideo Kojima: The Creative Gene", author: "Hideo Kojima", price: 1299, hotSale: true },
  { id: 72, title: "Sid Meier’s Memoir!", author: "Sid Meier", price: 1099, hotSale: true },
  { id: 73, title: "The Art of Naughty Dog", author: "Naughty Dog Studios", price: 1499, hotSale: true },
  { id: 74, title: "Miyamoto: The Man Behind Mario", author: "Jeff Ryan", price: 1399, hotSale: true },
  { id: 75, title: "John Romero: Doom Guy", author: "John Romero", price: 1599, hotSale: true },
  { id: 76, title: "Carmack & Romero: The Masters of FPS", author: "David Kushner", price: 1699, hotSale: true },
  { id: 77, title: "Ken Levine: The Mind Behind Bioshock", author: "Geoff Keighley", price: 1499, hotSale: true },
  { id: 78, title: "The Making of Final Fantasy", author: "Yoshitaka Amano", price: 1799, hotSale: true },
  { id: 79, title: "The Legend of Zelda: Creating a Classic", author: "Nintendo", price: 1999, hotSale: true },
  { id: 80, title: "The Last of Us: Official Art & Story", author: "Neil Druckmann", price: 1899, hotSale: true },
  { id: 81, title: "Metro 2033", author: "Dmitry Glukhovsky", price: 499, tag: "metro" },
  { id: 82, title: "Metro 2034", author: "Dmitry Glukhovsky", price: 520, tag: "metro" },
  { id: 83, title: "Metro 2035", author: "Dmitry Glukhovsky", price: 540, tag: "metro" },
  { id: 84, title: "Marvel Encyclopedia", author: "DK Publishing", price: 1599, tag: "marvel" },
  { id: 85, title: "Infinity Gauntlet", author: "Jim Starlin", price: 999, tag: "marvel" },
  { id: 86, title: "Civil War", author: "Mark Millar", price: 950, tag: "marvel" },
  { id: 87, title: "Spider-Man: Blue", author: "Jeph Loeb", price: 899, tag: "marvel" },
  { id: 88, title: "X-Men: Days of Future Past", author: "Chris Claremont", price: 920, tag: "marvel" },
  { id: 89, title: "Batman: The Killing Joke", author: "Alan Moore", price: 899, tag: "dc" },
  { id: 90, title: "Watchmen", author: "Alan Moore", price: 1099, tag: "dc" },
  { id: 91, title: "Superman: Red Son", author: "Mark Millar", price: 940, tag: "dc" },
  { id: 92, title: "Justice League: Origin", author: "Geoff Johns", price: 880, tag: "dc" },
  { id: 93, title: "The Flash: Rebirth", author: "Geoff Johns", price: 860, tag: "dc" },
  { id: 94, title: "Naruto Vol. 1", author: "Masashi Kishimoto", price: 399, tag: "manga" },
  { id: 95, title: "One Piece Vol. 1", author: "Eiichiro Oda", price: 420, tag: "manga" },
  { id: 96, title: "Attack on Titan Vol. 1", author: "Hajime Isayama", price: 430, tag: "manga" },
  { id: 97, title: "Death Note Vol. 1", author: "Tsugumi Ohba", price: 440, tag: "manga" },
  { id: 98, title: "Demon Slayer Vol. 1", author: "Koyoharu Gotouge", price: 460, tag: "manga" },
  { id: 99, title: "My Hero Academia Vol. 1", author: "Kohei Horikoshi", price: 450, tag: "manga" },
  { id: 100, title: "Tokyo Ghoul Vol. 1", author: "Sui Ishida", price: 470, tag: "manga" }
];
